// `npmctl docs` — generates the command reference by walking the cobra tree.
//
// Generated rather than hand-written so the skill's reference cannot drift from the
// binary. A test compares the two.
package cli

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/nnmduc/npmctl/internal/exitcode"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// pflagFlag aliases pflag.Flag so the visitor signature stays readable.
type pflagFlag = pflag.Flag

// writeTiers records which commands carry which gate tier, so the generated reference
// tells the reader what confirmation each write needs.
var writeTiers = map[string]Tier{
	"host create": TierNormal, "host update": TierNormal,
	"host enable": TierNormal, "host disable": TierNormal,
	"host rm": TierDestructive,

	"redirect create": TierNormal, "redirect update": TierNormal,
	"redirect enable": TierNormal, "redirect disable": TierNormal,
	"redirect rm": TierDestructive,

	"dead-host create": TierNormal, "dead-host update": TierNormal,
	"dead-host enable": TierNormal, "dead-host disable": TierNormal,
	"dead-host rm": TierDestructive,

	"stream create": TierNormal, "stream update": TierNormal,
	"stream enable": TierNormal, "stream disable": TierNormal,
	"stream rm": TierDestructive,

	"acl create": TierNormal, "acl update": TierNormal,
	"acl rm": TierDestructive,

	"cert create": TierNormal, "cert renew": TierNormal, "cert upload": TierNormal,
	"cert rm": TierDestructive,

	"undo apply": TierPrivileged,
}

func newDocsCommand(f *globalFlags) *cobra.Command {
	var outPath, format string
	cmd := &cobra.Command{
		Use:   "docs",
		Short: "Generate the command reference as Markdown",
		RunE: func(cmd *cobra.Command, _ []string) error {
			rt, err := newRuntime(f)
			if err != nil {
				return err
			}
			if format != "markdown" {
				return exitcode.New(exitcode.Usage, "only --format markdown is supported, got %q", format)
			}
			root, _ := NewRootCommand()
			doc := renderCommandReference(root)

			if outPath == "" {
				_, err := fmt.Fprint(rt.stdout, doc)
				return err
			}
			if err := os.WriteFile(expandUser(outPath), []byte(doc), 0o644); err != nil {
				return exitcode.Wrap(exitcode.Generic, err, "write %s", outPath)
			}
			fmt.Fprintf(rt.stderr, "wrote %s\n", outPath)
			return nil
		},
	}
	cmd.Flags().StringVar(&outPath, "out", "", "write to this file instead of stdout")
	cmd.Flags().StringVar(&format, "format", "markdown", "output format (markdown)")
	return cmd
}

// renderCommandReference walks the tree and emits Markdown.
func renderCommandReference(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString("# npmctl command reference\n\n")
	b.WriteString("Generated by `npmctl docs`. Do not edit by hand — regenerate instead, so this\n")
	b.WriteString("file cannot drift from the binary.\n\n")
	b.WriteString(fmt.Sprintf("Version: `%s`\n\n", version))

	b.WriteString("## Exit codes\n\n")
	b.WriteString("| Code | Meaning |\n|---|---|\n")
	for _, row := range [][2]string{
		{"0", "success"},
		{"1", "generic error"},
		{"2", "usage error"},
		{"3", "refused, or needs a confirmation that was not given"},
		{"4", "auth failure (credentials rejected)"},
		{"5", "not found"},
		{"6", "NPM returned an error"},
		{"7", "network error — a mutating write MAY have applied"},
		{"8", "applied, but the nginx reload failed"},
		{"9", "interactive re-authentication required"},
	} {
		fmt.Fprintf(&b, "| %s | %s |\n", row[0], row[1])
	}

	b.WriteString("\n## Write gate\n\n")
	b.WriteString("Every mutation requires **both** `NPMCTL_ALLOW_WRITE=1` in the environment and\n")
	b.WriteString("`--yes` on the command line. `--dry-run` previews any mutation and issues no\n")
	b.WriteString("mutating request.\n\n")
	b.WriteString("| Tier | Additional requirement |\n|---|---|\n")
	b.WriteString("| normal | none beyond the two factors |\n")
	b.WriteString("| destructive | a dependency scan, plus `--cascade-ack` when dependents exist |\n")
	b.WriteString("| privileged | an interactive terminal and a typed confirmation |\n\n")

	b.WriteString("## Global flags\n\n")
	writeFlagTable(&b, root, true)

	b.WriteString("\n## Commands\n\n")
	writeCommandSection(&b, root, "")
	return b.String()
}

func writeCommandSection(b *strings.Builder, cmd *cobra.Command, prefix string) {
	subs := cmd.Commands()
	sort.Slice(subs, func(i, j int) bool { return subs[i].Name() < subs[j].Name() })

	for _, sub := range subs {
		if sub.Hidden || sub.Name() == "help" || sub.Name() == "completion" {
			continue
		}
		path := strings.TrimSpace(prefix + " " + sub.Name())
		depth := len(strings.Fields(path)) + 2
		if depth > 6 {
			depth = 6
		}
		fmt.Fprintf(b, "%s `%s`\n\n", strings.Repeat("#", depth), path)

		if sub.Short != "" {
			fmt.Fprintf(b, "%s\n\n", sub.Short)
		}
		if tier, ok := writeTiers[path]; ok {
			fmt.Fprintf(b, "**Write** — tier: %s. Requires `NPMCTL_ALLOW_WRITE=1` and `--yes`.\n\n", tier)
		}
		if sub.Long != "" && sub.Long != sub.Short {
			fmt.Fprintf(b, "```text\n%s\n```\n\n", strings.TrimSpace(sub.Long))
		}
		if sub.Runnable() {
			// UseLine() already carries the full path including the binary name.
			fmt.Fprintf(b, "Usage: `%s`\n\n", sub.UseLine())
		}
		if sub.HasAvailableLocalFlags() {
			writeFlagTable(b, sub, false)
			b.WriteString("\n")
		}
		writeCommandSection(b, sub, path)
	}
}

func writeFlagTable(b *strings.Builder, cmd *cobra.Command, persistent bool) {
	flags := cmd.LocalFlags()
	if persistent {
		flags = cmd.PersistentFlags()
	}
	type row struct{ name, shorthand, usage, def string }
	var rows []row
	flags.VisitAll(func(f *pflagFlag) {
		if f.Hidden {
			return
		}
		rows = append(rows, row{name: f.Name, shorthand: f.Shorthand, usage: f.Usage, def: f.DefValue})
	})
	if len(rows) == 0 {
		return
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].name < rows[j].name })
	b.WriteString("| Flag | Default | Description |\n|---|---|---|\n")
	for _, r := range rows {
		name := "`--" + r.name + "`"
		if r.shorthand != "" {
			name = "`-" + r.shorthand + "`, " + name
		}
		def := r.def
		if def == "" {
			def = "—"
		}
		fmt.Fprintf(b, "| %s | `%s` | %s |\n", name, def, escapePipes(r.usage))
	}
}

func escapePipes(s string) string { return strings.ReplaceAll(s, "|", `\|`) }
